config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'

  root to: 'things#index'

  get 'things/index_ajax'
  get 'things/create_random'
  get 'things/destroy_all'
  get 'things/cookie_show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/thing.rb
class Thing < ApplicationRecord
end

app/controllers/application_controller.rb
include Pagy::Backend

class ApplicationController < ActionController::Base
end

app/controllers/things_controller.rb
include Pagy::Backend

class ThingsController < ApplicationController
  def index
    @pagy, @things = pagy(Thing.all)
  end

  def index_ajax
    @pagy, @things = pagy(Thing.all, link_extra: 'data-remote="true"')
  end

  def create_random
    GenerateRandomThingJob.set(wait: 10.seconds).perform_later
    redirect_to action: :index
  end

  def destroy_all
    Thing.all.destroy_all
    redirect_to action: :index
  end

  def cookie_show
    cookies[:normal_cookie] = 'normal cookie'
    cookies.permanent[:demo_permanent] = 'permanent cookie'
    cookies.encrypted[:demo_encrypted] = 'encrypted cookie'
    cookies.signed[:demo_signed] = 'signed cookie'
    cookies[:demo_httponly] = {value: 'http only', expires: Time.current + 1.hour, httponly: true}

    # SameSite
    cookies[:demo_samesite_lax] = {value: 'SameSite Lax', expires: Time.current + 2.hour, same_site: :lax}
    cookies[:demo_samesite_strict] = {value: 'SameSite Strict', expires: Time.current + 2.hour, same_site: :strict}

    session[:user_id] = 100
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsThings</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/templates/_nav.html.erb
<%#
  This template is i18n-ready: if you don't use i18n, then you can replace the pagy_t
  calls with the actual strings ("&lsaquo; Prev", "Next &rsaquo;", "&hellip;").
  The link variable is set to a proc that returns the link tag.
  Usage: link.call( page_number [, text [, extra_attributes_string ]])
-%>
<% link = pagy_link_proc(pagy, 'class="page-link"') -%>
<%#                            -%><nav aria-label="pager"  class="pagy-bootstrap-nav pagination" role="navigation">
<%#                            -%>  <ul class="pagination">
<% if pagy.prev                -%>    <li class="page-item prev"><%== link.call(pagy.prev, pagy_t('pagy.nav.prev'), 'aria-label="previous"') %></li>
<% else                        -%>    <li class="page-item prev disabled"><a href="#" class="page-link"><%== pagy_t('pagy.nav.prev') %> VH</a></li>
<% end                         -%>
<% pagy.series.each do |item| # series example: [1, :gap, 7, 8, "9", 10, 11, :gap, 36] -%>
<%   if    item.is_a?(Integer) -%>    <li class="page-item"><%== link.call(item) %></li>
<%   elsif item.is_a?(String)  -%>    <li class="page-item active"><%== link.call(item) %></li>
<%   elsif item == :gap        -%>    <li class="page-item disabled gap"><a href="#" class="page-link"><%== pagy_t('pagy.nav.gap') %></a></li>
<%   end                       -%>
<% end                         -%>
<% if pagy.next                -%>    <li class="page-item next"><%== link.call(pagy.next, pagy_t('pagy.nav.next'), 'aria-label="next"') %></li>
<% else                        -%>    <li class="page-item next disabled"><a href="#" class="page-link"><%== pagy_t('pagy.nav.next') %></a></li>
<% end                         -%>
<%#                            -%>  </ul>
<%#                            -%></nav>

app/views/things/_table_js.html.erb
<legend>Thing</legend>
<p>
  <%= link_to 'Create Random thing', things_create_random_path %> |
  <%= link_to 'Destroy All', things_destroy_all_path %> |
  <%= link_to 'Refresh', root_path %>
</p>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
    </tr>
  </thead>
  <tbody>
    <% @things.each do |thing| %>
      <tr>
        <td><%= thing.name %></td>
        <td><%= thing.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr/>
<%== pagy_bootstrap_nav_js(@pagy) %>

app/views/things/cookie_show.html.erb
<div>
  <div>COOKIE</div>
  <img src='https://github.com/account' width='1' height='1' />
  <a href='https://github.com/'>Github</a>
  <a href='http://localhost:3000'>Home</a>
  <a href='http://vhwiki:3000'>vhwiki</a>
</div>

app/views/things/index.html.erb
<legend>Thing</legend>
<p>
  <%= link_to 'Create Random thing', things_create_random_path %> |
  <%= link_to 'Destroy All', things_destroy_all_path %> |
  <%= link_to 'Refresh', root_path %>
</p>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
    </tr>
  </thead>
  <tbody>
    <% @things.each do |thing| %>
      <tr>
        <td><%= thing.name %></td>
        <td><%= thing.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr/>
<div>Default style</div>
<%== pagy_info(@pagy) %>
<%== pagy_nav(@pagy) %>

<hr/>
<div>Bootstrap style</div>
<div>
  <%= @pagy.from %> - <%= @pagy.to %> / <%= @pagy.count %>
</div>
<%== pagy_bootstrap_nav(@pagy) %>
<%== render partial: 'templates/nav', locals: {pagy: @pagy} %>

app/views/things/index_ajax.html.erb
<div id='container'>
  <%= render partial: 'table_js' %>
</div>

app/views/things/index_ajax.js.erb
$('#container').html("<%= j(render 'table_js')%>");
Pagy.init(document.getElementById('container'));